CREATE USER airflow;
CREATE DATABASE airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;

CREATE USER grafana;
CREATE DATABASE grafana;
GRANT ALL PRIVILEGES ON DATABASE grafana TO grafana;


CREATE USER airflow2;
CREATE DATABASE airflow2;
GRANT ALL PRIVILEGES ON DATABASE airflow2 TO airflow2;

CREATE USER grafana2;
CREATE DATABASE grafana2;
GRANT ALL PRIVILEGES ON DATABASE grafana2 TO grafana2;
